os:
  - osx
  - linux

sudo: required

language: rust

rust:
  - stable

install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgmp-dev && travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install haskell-stack && brew install llvm; fi

script:
  - ./configure && make && make test

cache:
  directories:
  - ./rust-bindgen
  - ./frontend/.stack-work/install
  - $HOME/.stack
