os:
  - osx
  - linux
sudo: required
language: rust
rust:
  - stable
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install haskell-stack && brew install llvm; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install -y llvm-dev haskell-stack; fi

script:
  - ./configure && make && make test

cache:
  directories:
  - ./rust-bindgen
  - ./frontend/.stack-work/install
  - $HOME/.stack
