os:
  - osx

install:
  - brew update
  - brew install rust
  - brew install haskell-stack
  - brew install llvm

script:
  - sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
  - ./configure
  - make
  - make test

cache:
  directories:
  - ./rust-bindgen
  - ./frontend/.stack-work
  - $HOME/.stack
