os:
  - osx

install:
  - brew update
  - brew install rust
  - brew install haskell-stack
  - brew install llvm

script:
  - ./configure
  - make
  - make test

cache:
  directories:
  - ./rust-bindgen
